package main

func main() {

	consoleClear()
	// forLoop()
	// conditions()
	// arrays()
	// slices()
	// mapfn()
	// rangeFn()
	// funcs()
	// variadics()
	// closures()
	// recursion()
	// pointers()
	// stringsAndRunes()
	// structImpl()
	// structMethods()
	// interfaces()
	// structs()
	// methods()
	// structEmbedding()
	// generics()
	// errorLearn()
	// customError()
	// goRoutineTest()
	// channelTest()
	// channelBufferedTest()
	// channelSyncTest()
	channelDirectionTest()
	// luhnCC([]int{7, 9, 9, 2, 7, 3, 9, 8, 7, 1, 3})
}
